import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 w-full border-b bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60 dark:bg-black/60">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <a href="/" className="flex items-center gap-2 font-semibold">
              <span className="inline-block h-6 w-6 rounded bg-black dark:bg-white" />
              <span>Blogging</span>
            </a>
            <nav className="hidden md:flex items-center gap-6 text-sm">
              <a className="hover:underline" href="/">Home</a>
              <a className="hover:underline" href="/blog">Blog</a>
              <a className="hover:underline" href="/dashboard">Dashboard</a>
            </nav>
            <button className="md:hidden inline-flex items-center justify-center rounded-md border px-3 py-2 text-sm">
              Menu
            </button>
          </div>
        </header>
        <main className="min-h-[calc(100vh-8rem)]">{children}</main>
        <footer className="border-t">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-8 text-sm text-muted-foreground flex flex-col sm:flex-row items-center justify-between gap-4">
            <p>© {new Date().getFullYear()} Blogging. All rights reserved.</p>
            <div className="flex items-center gap-4">
              <a className="hover:underline" href="/blog">All Posts</a>
              <a className="hover:underline" href="/dashboard">Dashboard</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
